SlnFarmacia_David/PrjFarmacia_David/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PrjFarmacia_David.DAO;
using PrjFarmacia_David.Models;

namespace PrjFarmacia_David.Controllers
{
    public class ClientesController : Controller
    {
        private readonly ClientesDAO daocli;
        public ClientesController(ClientesDAO cli)
        {
            daocli = cli;
        }


        // GET: ClientesController
        public ActionResult IndexClientes(int nropagina = 0)
        {
            var listado = daocli.getClientes();
            // PAGINACION
            int filas_pagina = 7;
            int cantidad = listado.Count;
            int paginas = 0;
            if (cantidad % filas_pagina > 0)
                paginas = (cantidad / filas_pagina) + 1;
            else
                paginas = cantidad / filas_pagina;
            //
            ViewBag.PAGINAS = paginas;
            //
            ViewBag.nropagina = nropagina;

            return View(listado.Skip(nropagina * filas_pagina).Take(filas_pagina));
        }

        // GET: ClientesController/Details/5
        public ActionResult DetailsCliente(int id)
        {
            var buscar = daocli.getClientes().Find(cli => cli.Id == id);
            return View(buscar);
        }

        // GET: ClientesController/Create
        public ActionResult CreateCliente()
        {
            Cliente nuevo = new Cliente();
            return View(nuevo);
        }

        // POST: ClientesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCliente(Cliente obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["mensaje"] = daocli.GrabarCliente(obj);
                    return RedirectToAction(nameof(IndexClientes));
                }
            }
            catch(Exception ex)
            {
                ViewBag.mensaje = "Fail: " + ex.Message;
            }
            return View(obj);
        }

        // GET: ClientesController/Edit/5
        public ActionResult EditCliente(int id)
        {
            Cliente buscar = daocli.getClientes().Find(cli => cli.Id == id)!;
            return View(buscar);
        }

        // POST: ClientesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditCliente(int id, Cliente obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["mensaje"] = daocli.GrabarCliente(obj);
                    return RedirectToAction(nameof(IndexClientes));
                }
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View(obj);
        }

        // GET: ClientesController/Delete/5
        public ActionResult DeleteCliente(int id)
        {
            Cliente buscar = daocli.getClientes().Find(cli => cli.Id == id)!;
            return View(buscar);
        }

        // POST: ClientesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCliente(int id, IFormCollection collection)
        {
            try
            {
                TempData["mensaje"] = daocli.EliminarCliente(id);
                return RedirectToAction(nameof(IndexClientes));
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View();
        }
        public ActionResult ClientesxNombre(string letraNom = "")
        {
            var listado = daocli.getClientesNombre(letraNom);
            return View(listado);
        }
    }
}

SlnFarmacia_David/PrjFarmacia_David/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PrjFarmacia_David.DAO;
using PrjFarmacia_David.Models;

namespace PrjFarmacia_David.Controllers
{
    public class ProductosController : Controller
    {
        private readonly ProductosDAO daopro;

        public ProductosController(ProductosDAO pro)
        {
            daopro = pro;
        }


        // GET: ProductosController
        public ActionResult IndexProductos(int nropagina=0)
        {
            var listado = daopro.getProductos();
            // PAGINACION
            int filas_pagina = 7;
            int cantidad = listado.Count;
            int paginas = 0;
            if (cantidad % filas_pagina > 0)
                paginas = (cantidad / filas_pagina) + 1;
            else
                paginas = cantidad / filas_pagina;
            //
            ViewBag.PAGINAS = paginas;
            //
            ViewBag.nropagina = nropagina;

            return View(listado.Skip(nropagina * filas_pagina).Take(filas_pagina));
        }

        // GET: ProductosController/Details/5
        public ActionResult DetailsProducto(int id)
        {
            var buscar = daopro.getProductos().Find(pro => pro.Id == id);

            return View(buscar);
        }

        // GET: ProductosController/Create
        public ActionResult CreateProducto()
        {
            Producto nuevo = new Producto();

            return View(nuevo);
        }

        // POST: ProductosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProducto(Producto obj)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    TempData["mensaje"] = daopro.GrabarProducto(obj);
                    return RedirectToAction(nameof(IndexProductos));
                }
            }
            catch(Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View(obj);
        }

        // GET: ProductosController/Edit/5
        public ActionResult EditProducto(int id)
        {
            Producto buscar = daopro.getProductos().Find(pro => pro.Id == id)!;
            return View(buscar);
        }

        // POST: ProductosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProducto(int id, Producto obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TempData["mensaje"] = daopro.GrabarProducto(obj);
                    return RedirectToAction(nameof(IndexProductos));
                }                
            }
            catch(Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View(obj);
        }

        // GET: ProductosController/Delete/5
        public ActionResult DeleteProducto(int id)
        {
            Producto buscar = daopro.getProductos().Find(pro => pro.Id == id)!;
            return View(buscar);
        }

        // POST: ProductosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProducto(int id, IFormCollection collection)
        {
            try
            {
                TempData["mensaje"] = daopro.EliminarProducto(id);
                return RedirectToAction(nameof(IndexProductos));
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = "Error: " + ex.Message;
            }
            return View();
        }
        public ActionResult ProductosXNombre(string letraNom = "")
        {
            var listado = daopro.getProductosNombre(letraNom);
            return View(listado);
        }
    }
}

SlnFarmacia_David/PrjFarmacia_David/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using PrjFarmacia_David.DAO;
using PrjFarmacia_David.Models;

namespace PrjFarmacia_David.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly UsuariosDAO dao;
        public UsuarioController(UsuariosDAO usu)
        {
            dao = usu;
        }
        // GET
        public IActionResult ValidarIngreso()
        {

            return View();
        }
        // POST
        [HttpPost]
        public IActionResult ValidarIngreso(Usuario obj)
        {
            if (ModelState.IsValid)
            {
                string mensaje = dao.Validar_Usuario(obj);
                if (mensaje[0].ToString() == "B")
                {
                    TempData["mensaje"] = mensaje;
                    return RedirectToAction("Index", "Home");
                }
                else
                    ViewBag.mensaje = mensaje;
            }

            return View(obj);

        }
    }
}

SlnFarmacia_David/PrjFarmacia_David/Controllers/VentasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using PrjFarmacia_David.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using System.Transactions;

namespace PrjFarmacia_David.Controllers
{
    public class VentasController : Controller
    {
        List<ReporteVentas> listaventas = new List<ReporteVentas>();

        public async Task<List<ReporteVentas>> traerVentas()
        {
            using (HttpClient cliente = new HttpClient())
            {
                // realizar la solicitud
                var respuesta = await cliente.GetAsync(
                    "http://localhost:5031/api/ReporteVentasAPI/GetReporteVentas");
                // convertir el contenido devuelto a un string
                string cadena = await respuesta.Content.ReadAsStringAsync();
                // deserializamos la cadena json a una lista de medicos 
                return JsonConvert.DeserializeObject<List<ReporteVentas>>(cadena)!;
            }
        }
        public async Task<List<Cliente>> traerCliente()
        {
            using (HttpClient cliente = new HttpClient())
            {
                // realizar la solicitud
                var respuesta = await cliente.GetAsync(
                    "http://localhost:5031/api/ReporteVentasAPI/GetCliente");
                // convertir el contenido devuelto a un string
                string cadena = await respuesta.Content.ReadAsStringAsync();
                // deserializamos la cadena json a una lista de especialidades 
                return JsonConvert.DeserializeObject<List<Cliente>>(cadena)!;
            }
        }
        public async Task<ActionResult> IndexVentas(int nropagina=0)
        {
            listaventas = await traerVentas();
            //
            ViewBag.contador = listaventas.Count;
            //
            // PAGINACION
            int filas_pagina = 7;
            int cantidad = listaventas.Count;
            int paginas = 0;
            if (cantidad % filas_pagina > 0)
                paginas = (cantidad / filas_pagina) + 1;
            else
                paginas = cantidad / filas_pagina;
            //
            ViewBag.PAGINAS = paginas;
            //
            ViewBag.nropagina = nropagina;

            return View(listaventas.Skip(nropagina * filas_pagina).Take(filas_pagina));
        }

        //
        public async Task<List<ReporteVentasPorCliente>> traerClientexNombre(int id)
        {
            using (HttpClient cliente = new HttpClient())
            {
                // realizar la solicitud
                var respuesta = await cliente.GetAsync(
                    "http://localhost:5031/api/ReporteVentasAPI/GetVentasCliente/" + id);
                // convertir el contenido devuelto a un string
                string cadena = await respuesta.Content.ReadAsStringAsync();
                // deserializamos la cadena json a una lista de medicos 
                return JsonConvert.DeserializeObject<List<ReporteVentasPorCliente>>(cadena)!;
            }
        }

        // GET
        public async Task<IActionResult> ClienteNombre(int id)
        {
            var listado = await traerClientexNombre(id);

            if (listado == null) listado = new List<ReporteVentasPorCliente>();

            ViewBag.nombreCliente = new SelectList(
                await traerCliente(), "Id", "Nombre");

            return View(listado);
        }

    }
}

SlnFarmacia_David/PrjFarmacia_David/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoFarmacia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoFarmacia.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoFarmacia</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Clientes" asp-action="IndexClientes">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Productos" asp-action="IndexProductos">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Ventas" asp-action="IndexVentas">Reporte Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Carrito" asp-action="IndexProductos">Realizar Ventas</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-nav">
                    <a class="nav-link" asp-area="" asp-controller="Usuario" asp-action="ValidarIngreso">Cerrar Sesión</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SlnFarmacia_David/PrjFarmacia_David/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoFarmacia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoFarmacia.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>